#!/bin/bash

export BOOST_LIBRARYDIR="/usr/lib64/"
#export CMAKE_LIBRARY_PATH="/usr/lib64:$CMAKE_LIBRARY_PATH"
#export CMAKE_INCLUDE_PATH="/usr/include/boost-1_49:$CMAKE_INCLUDE_PATH"
rm -R -f build
mkdir build
cd build
rm -R -f linux64
mkdir linux64
cd linux64
rm -R -f gcc
mkdir gcc
cd gcc
cmake ../../.. -DCMAKE_INSTALL_PREFIX=next_install_linux64 -DBUILD_DOCUMENTATION=ON -DBUILD_DOCUMENTATION_HTML=ON -DDOCBOOK_AUTOCONFIG=ON -DBUILD_QUICKBOOK=ON -DENABLE_DEBUG=ON -DENABLE_RELEASE=OFF -DBUILD_TESTS=ALL
cd ..
rm -R -f clang
mkdir clang
cd clang
cmake ../../.. -DCMAKE_INSTALL_PREFIX=next_install_linux64 -DBUILD_DOCUMENTATION=ON -DBUILD_DOCUMENTATION_HTML=ON -DDOCBOOK_AUTOCONFIG=ON -DBUILD_QUICKBOOK=ON -DENABLE_DEBUG=ON -DENABLE_RELEASE=OFF -DBUILD_TESTS=ALL -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
